latex_names = {
  '4l': '$4\ell$',
  '2e2mu': '$2e2\mu$',
  'mass4l': '$m_{4l}$',
  'mass4l_zzfloating': '$m_{4l}$',
  'njets_pt30_eta4p7': '$N_{jet}$',
  'pT4l': '$p_{T}^{H}$',
  'rapidity4l': '$|y_{H}|$',
  'costhetaZ1': '$cos(\\theta_{1})$',
  'costhetaZ2': '$cos(\\theta_{2})$',
  'phi': '$\\Phi$',
  'phistar': '$\\Phi^{\\star}$',
  'costhetastar': '$cos(\\theta^{*})$',
  'massZ1': '$m_{Z1}$',
  'massZ2': '$m_{Z2}$',
  'pTj1': '$p_{T}^{(j1, 4.7)}$',
  'pTHj': '$p_{T}^{Hj}$',
  'mHj': '$m_{Hj}$',
  'pTj2': '$p_{T}^{(j2, 4.7)}$',
  'mjj': '$m_{jj}$',
  'absdetajj': '$|\\Delta\\Eta_{jj}|$',
  'dphijj': '$|\\Delta\\Phi_{jj}|$',
  'pTHjj': '$p_{T}^{Hjj}$',
  'TCjmax': '$\\mathrm{T}_{\\mathrm{C},{j}}$',
  'TBjmax': '$\\mathrm{T}_{\\mathrm{B},{j}}$',
  'D0m': '$D_{0m}$',
  'Dcp': '$D_{cp}$',
  'D0hp': '$D_{0h^{+}}$',
  'Dint': '$D_{int}$',
  'DL1': '$D_{\\Lambda1}$',
  'DL1Zg': '$D_{\\Lambda1,Z\\gamma}$',
}
